# Generated by Django 5.0.6 on 2024-07-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedilabApp', '0004_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('phone', models.CharField(max_length=10)),
                ('doctor', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=10)),
                ('date', models.DateField()),
            ],
        ),
    ]
